import type { Metadata } from "next";
import Link from "next/link";
import { Container } from "@/components/Container";
import { Button } from "@/components/Button";
import { SectionHeading } from "@/components/SectionHeading";
import { Reveal } from "@/components/Reveal";
import { InfoCard } from "@/components/InfoCard";
import { ClosingCTA } from "@/components/ClosingCTA";
import { RewardsVisual } from "@/components/visuals/RewardsVisual";
import { pageMetadata } from "@/lib/seo";
import { siteConfig } from "@/lib/constants";

export const metadata: Metadata = pageMetadata({
  title: "Rewards, Coupons & Referrals",
  description:
    "Three independent mechanisms for Shopify, Review Rewards, standalone Coupons, and Referrals, each issuing a real discount code automatically.",
  path: "/rewards",
});

const MECHANISMS = [
  {
    name: "Review Rewards",
    description: "A discount for a review meeting conditions you set, minimum rating, verified purchase, a photo or a video.",
  },
  {
    name: "Coupons",
    description: "A standalone promotional campaign, completely independent of any review, for whatever campaign you're running.",
  },
  {
    name: "Referrals",
    description: "A code your customers share. The referrer is rewarded the moment a friend's real order uses it, never before.",
  },
];

export default function RewardsPage() {
  return (
    <>
      <section className="pt-24 pb-16 md:pt-32 md:pb-20">
        <Container className="grid grid-cols-1 items-center gap-14 lg:grid-cols-2">
          <div className="flex flex-col gap-5">
            <span className="text-xs font-semibold tracking-[0.02em] text-accent">Rewards & Referrals</span>
            <h1 className="text-hero font-semibold leading-[1.08] tracking-[-0.035em] text-foreground">
              Give customers a real reason to come back.
            </h1>
            <p className="text-lg leading-relaxed text-muted-foreground">
              Every discount code issued through Imagyn Reviews is a real Shopify discount, created automatically,
              never generated by hand, and never issued until the condition it&apos;s tied to is actually met.
            </p>
            <div className="mt-2 flex flex-wrap gap-4">
              <Button href={siteConfig.appStoreUrl} size="lg">
                Get Started
              </Button>
              <Button href="/features" variant="secondary" size="lg">
                See all features
              </Button>
            </div>
          </div>
          <Reveal>
            <RewardsVisual />
          </Reveal>
        </Container>
      </section>

      <section className="border-t border-border py-24 md:py-28">
        <Container>
          <SectionHeading eyebrow="Three mechanisms" title="Independent, automatic, and honest about when a reward is earned." align="left" />
          <div className="mt-14 grid grid-cols-1 gap-6 md:grid-cols-3">
            {MECHANISMS.map((item, index) => (
              <Reveal key={item.name} delayMs={index * 100}>
                <InfoCard index={index} title={item.name} description={item.description} />
              </Reveal>
            ))}
          </div>
        </Container>
      </section>

      <section className="border-t border-border py-16">
        <Container className="flex flex-wrap items-center justify-between gap-4">
          <p className="text-sm text-muted-foreground">Related</p>
          <div className="flex flex-wrap gap-6">
            <a href="/trust" className="text-[15px] font-medium text-foreground hover:text-accent">
              Trust & Certification →
            </a>
            <Link href="/ai" className="text-[15px] font-medium text-foreground hover:text-accent">
              AI Insights →
            </Link>
            <a href="/features" className="text-[15px] font-medium text-foreground hover:text-accent">
              All features →
            </a>
          </div>
        </Container>
      </section>

      <ClosingCTA title="Turn one review into the next five customers." />
    </>
  );
}
