import type { Metadata } from "next";
import { Container } from "@/components/Container";
import { Button } from "@/components/Button";
import { SectionHeading } from "@/components/SectionHeading";
import { Reveal } from "@/components/Reveal";
import { RewardsVisual } from "@/components/visuals/RewardsVisual";
import { pageMetadata } from "@/lib/seo";

export const metadata: Metadata = pageMetadata({
  title: "Rewards, Coupons & Referrals",
  description:
    "Three independent mechanisms for Shopify — Review Rewards, standalone Coupons, and Referrals — each issuing a real discount code automatically.",
  path: "/rewards",
});

const MECHANISMS = [
  {
    name: "Review Rewards",
    description: "A discount for a review meeting conditions you set — minimum rating, verified purchase, a photo or a video.",
  },
  {
    name: "Coupons",
    description: "A standalone promotional campaign, completely independent of any review — for whatever campaign you're running.",
  },
  {
    name: "Referrals",
    description: "A code your customers share. The referrer is rewarded the moment a friend's real order uses it — never before.",
  },
];

export default function RewardsPage() {
  return (
    <>
      <section className="pt-24 pb-16 md:pt-32 md:pb-20">
        <Container className="grid items-center gap-14 lg:grid-cols-2">
          <div className="flex flex-col gap-5">
            <span className="text-xs font-semibold uppercase tracking-[0.2em] text-accent">Rewards & Referrals</span>
            <h1 className="text-[clamp(2rem,4.2vw,3.25rem)] font-semibold leading-[1.08] tracking-[-0.035em] text-foreground">
              Give customers a real reason to come back.
            </h1>
            <p className="text-lg leading-relaxed text-muted-foreground">
              Every discount code issued through Imagyn Reviews is a real Shopify discount — created automatically,
              never generated by hand, and never issued until the condition it&apos;s tied to is actually met.
            </p>
            <div className="mt-2 flex flex-wrap gap-4">
              <Button href="/pricing" size="lg">
                Get Started
              </Button>
              <Button href="/features" variant="secondary" size="lg">
                See all features
              </Button>
            </div>
          </div>
          <Reveal>
            <RewardsVisual />
          </Reveal>
        </Container>
      </section>

      <section className="border-t border-border py-24 md:py-28">
        <Container>
          <SectionHeading eyebrow="Three mechanisms" title="Independent, automatic, and honest about when a reward is earned." align="left" />
          <div className="mt-14 grid gap-6 md:grid-cols-3">
            {MECHANISMS.map((item, index) => (
              <Reveal key={item.name} delayMs={index * 100}>
                <div className="flex h-full flex-col gap-2 rounded-2xl border border-border bg-surface p-7">
                  <h3 className="text-lg font-semibold text-foreground">{item.name}</h3>
                  <p className="text-[15px] leading-relaxed text-muted-foreground">{item.description}</p>
                </div>
              </Reveal>
            ))}
          </div>
        </Container>
      </section>

      <section className="border-t border-border py-16">
        <Container className="flex flex-wrap items-center justify-between gap-4">
          <p className="text-sm text-muted-foreground">Related</p>
          <div className="flex flex-wrap gap-6">
            <a href="/ai" className="text-[15px] font-medium text-foreground hover:text-accent">
              AI Insights →
            </a>
            <a href="/features" className="text-[15px] font-medium text-foreground hover:text-accent">
              All features →
            </a>
          </div>
        </Container>
      </section>

      <section className="border-t border-border py-28 md:py-36">
        <Container>
          <div className="flex flex-col items-center gap-6 rounded-[32px] bg-surface px-8 py-16 text-center shadow-soft md:px-16">
            <h2 className="max-w-2xl text-[clamp(1.75rem,3.4vw,2.75rem)] font-semibold leading-[1.1] tracking-[-0.035em] text-foreground">
              Turn one review into the next five customers.
            </h2>
            <Button href="/pricing" size="lg">
              Get Started
            </Button>
          </div>
        </Container>
      </section>
    </>
  );
}
